name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
    - name: Set-up Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: 14.x
    - name: Install Firebase Tools
      run: npm install -g firebase-tools@12
    - name: Install NPM dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" -f
