name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
    - name: Set-up Node.js 16.x
      uses: actions/setup-node@master
      with:
        node-version: 16.x
    - name: Install Firebase Tools
      run: npm install -g firebase-tools@12
    - name: Install NPM dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > ${{ github.workspace }}/gcloud-key.json
    - name: Deploy
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-key.json
      run: firebase deploy
